apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-2
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginx
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: app-data
          mountPath: /mnt/data
          readOnly: true
  volumes:
    - name: app-data
      emptyDir: {}
