apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: non-admin-api-allow
spec:
  podSelector:
    matchExpressions:
      - key: role
        operator: In
        values:
          - front-end
          - back-end-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: role
                operator: In
                values:
                  - front-end
                  - back-end-api
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: role
                operator: In
                values:
                  - front-end
                  - back-end-api
